# Generated by Django 4.2.3 on 2023-07-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_category_rename_user_balance_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(),
        ),
    ]
